chore: updated documentations to include code examples
Eyevinn/whip pull request #114
Opened 2023-02-14 13:50 UTC by oshinongit

First take on how autogen documentation can look with code examples

2023-02-14 13:53 UTC, birme approved these changes
Looks good, just thinking though whether those that you marked as hidden actually should be private methods. But we can change that in another PR.

2023-02-14 14:26 UTC, bwallberg requested changes
The indentation is wrong sometimes, the `/**` first star should align with the bottom star `*/` ( like here: https://typedoc.org/tags/example/ ) 

Also every row of a comment should begin with `*`

2023-02-15 05:10 UTC, bwallberg commented on packages/sdk/src/index.ts
> +  video: true,
missing `*`

2023-02-15 05:11 UTC, bwallberg commented on packages/sdk/src/index.ts
> + *const mediaStream = await navigator.mediaDevices.getUserMedia({
missing space between `*` and `c`

2023-02-15 17:46 UTC, bwallberg approved these changes
LGTM!

2023-02-20 13:20 UTC, merged