fix: use sfu api key if present
Eyevinn/whip pull request #91
Opened 2022-09-12 08:27 UTC by marcusspangenberg

Closes #90

2022-09-12 08:53 UTC, birme approved these changes
Looks good. Just add the env key to the server endpoint README.
Or even better make it an option to the WhipEndpoint constructor.

2022-09-12 10:59 UTC, marcusspangenberg commented
> Looks good. Just add the env key to the server endpoint README. Or even better make it an option to the WhipEndpoint constructor.

Please have a look again, I moved all the mandatory setter calls to constructor parameters.

2022-09-13 05:33 UTC, birme requested changes
Keep and deprecate the removed exported methods to assign SFU origin and broadcaster clients.

2022-09-13 05:33 UTC, birme commented on packages/server/src/whip/sfu/sfuWhipResource.ts
> -  assignBroadcasterClients(broadcasterClientSfuPairs: BroadcasterClientSfuPair[]) {
Can we keep these two functions but mark as deprecated?
There are already some examples and components out there that uses them.

2022-09-13 13:40 UTC, birme approved these changes

2022-09-13 13:40 UTC, merged